# The Travis-CI configuration for colabtools is just a stub; tests for
# colabtools are run internally.

language: python
# We set sudo: true and dist: xenial to allow Python 3.7 testing; cf:
#   https://github.com/travis-ci/travis-ci/issues/9069
#   https://github.com/travis-ci/travis-ci/issues/9815
sudo: true
dist: xenial
python:
  - "2.7"
  - "3.6"
  - "3.7"

matrix:
  allow_failures:
    - python: "3.7"

notifications:
  recipients:
    - colaboratory-team+travis-ci@google.com

install: pip install tox-travis
script: tox
